############################# default configuration #############################

baseURL = "https://www.kokkolanbudo.fi"
title = "Kokkolan Budo"
theme = "bigspring-light"
defaultContentLanguage = 'fi'
defaultContentLanguageInSubdir = false
paginate = "3"          # post pagination 
summaryLength = "15"    # post excerpt

[markup.goldmark.renderer]
unsafe = true