############################# default parameters ################################
logo = "images/kokkolanbudo.webp"
logo_width = "175px"
logo2 = "images/kokkolanbudologowhite.webp"
description = "Kokkolan Budo ry - Kokkolalainen budo seura, joka tarjoaa mahdollisuuden harrastaa karatea, judoa sekä brasilialaista jujutsua."
author = "Roope Korpela"
image = "images/kokkolanbudo.webp" # this image will be used as fallback if a page has no image of its own

contact_bjj_action = "https://forms.un-static.com/forms/11e372eaba323a68693a3b6d654b22c81319e974" 
contact_judo_action = "https://forms.un-static.com/forms/710c018bafabc4b3d30ede2f24489f3dfb3e2c98" # contact form works with https://forms.un-static.com
contact_karate_action = "https://forms.un-static.com/forms/e6c73cd79cb7a0c95435e67f5777d2c39bd5ea1f" # contact form works with https://forms.un-static.com

blogCategoryType = "category"   # Type of pages to be rendered with a blog view

[navigation_button]
enable = true
label = "Liity joukkoon!"
link = "getstarted"

[startDates]
bjjCourseImage = "../../images/bjjclass.webp"
judoCourseImage = "../../images/judothrow2.webp"
