# Netlify CMS configuration file
backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: "static/images" # Media files will be stored in the repo under static/images
public_folder: "images"

collections:
- name: "uutiset" # Used in routes, e.g., /admin/collections/blog
  label: "Uutinen (Finnish)" # Used in the UI
  folder: "content/finnish/news" # The path to the folder where the documents are stored
  create: true # Allow users to create new documents in this collection
  slug: "{{slug}}-{{month}}-{{year}}" # Filename template, e.g., YYYY-MM-DD-title.md
  fields: # The fields for each document, usually in front matter
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Publish Date", name: "date", widget: "datetime"}
    - {label: "Featured Image", name: "image", widget: "image"}
    - {label: "Summary", name: "summary", widget: "markdown"}
    - {label: "Body", name: "body", widget: "markdown"}

- name: "news" # Used in routes, e.g., /admin/collections/blog
  label: "Uutinen (English)" # Used in the UI
  folder: "content/english/news" # The path to the folder where the documents are stored
  create: true # Allow users to create new documents in this collection
  slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  fields: # The fields for each document, usually in front matter
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Publish Date", name: "date", widget: "datetime"}
    - {label: "Featured Image", name: "image", widget: "image"}
    - {label: "Summary", name: "summary", widget: "markdown"}
    - {label: "Body", name: "body", widget: "markdown"}

- name: "pages" 
  label: "Pages"
  files:
    - file: "content/finnish/clubrules.md" 
      name: "clubrules-fi"
      label: "Dojo säännöt"
      fields:
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Body", name: "body", widget: "markdown"}

    - file: "content/finnish/karate.md" 
      name: "karate-fi"    
      label: "Karate (Finnish)"
      fields:
        - label: "Harjoitusajat"
          name: "timetable"
          widget: "object"
          fields:
            - {label: "Harjoitusaika", name: "timetable_item", widget: "list", fields: 
              [
                {label: "Harjoituksen nimi", name: "name", widget: "string", hint: "Esim. **Karaten ylemmät vyöt** tai **Karaten peruskussi**"},
                {label: "1. harjoitusaika", name: "time1", widget: "string", hint: "Kirjoita muodossa: **Maanantai klo 17:00-18:00**"},
                {label: "1. harjoituspaikka", name: "time1location", widget: "select", options: 
                [
                  "(Martial Arts Center, pieni puoli)",
                  "(Martial Arts Center, iso puoli)"
                ]},
                {label: "2. harjoitusaika", name: "time2", widget: "string", required: false, hint: "Kirjoita muodossa: **Maanantai klo 17:00-18:00**"},
                {label: "2. harjoituspaikka", name: "time2location", widget: "select", required: false, options: 
                [
                  "(Martial Arts Center, pieni puoli)",
                  "(Martial Arts Center, iso puoli)"
                ]}
              ]}
        - label: "Valmentajat"
          name: "coaches"
          widget: "object"
          fields: 
            - {label: "Valmentaja", name: "coach_item", widget: "list", fields: [
                {label: "Valmentajan nimi", name: "name", widget: "string"},
                {label: "Vyön nimi", name: "belt", widget: "string", hint: "Esim: **1. dan musta vyö**"},
                {label: "Vyön väri", name: "beltcolor", widget: "select", options: [
                      { label: "Musta", value: "#222" },
                      { label: "Purppura", value: "#5E3E8D" },
                      { label: "Ruskea", value: "#3f2a14" },
                      { label: "Sininen", value: "#355cb0" },
                      { label: "Ei tiedossa", value: "#DEDED9" }
                ]},
                {label: "Valmentajan kuva", name: "image", widget: "image", hint: "Ohje: 1. **Rajaa kuva neliön muotoiseksi**, niin että kasvot ja vyö näkyy. 2. **Poista kuvasta tausta** esim. tällä työkalulla: https://www.remove.bg/ 3. Muuta kuva tiedostomuotoon **.webp** esim. sivulla: https://webpconverter.org/ 4. Lopuksi nimeä tiedosto selkeästi valmentajan nimellä: **Roope Korpela.webp**"},
                {label: "Valmentajan rooli", name: "description", widget: "string", hint: "Esim: **Ylempien vöiden valmentaja** tai **Peruskurssin valmentaja**"},
                {label: "Valmentajan ohjaajakoulutus", name: "description2", widget: "string", required: false, hint: "Esim: **(1-tason junioriohjaaja)**"}
              ]}
        - {label: "Karaten harrastajille", name: "moreinfo", widget: "object", fields: [
              {label: "Sisältö", name: "content", widget: "markdown"}
            ]}
    
    - file: "content/english/karate.md" 
      name: "karate-en"    
      label: "Karate (English)"
      fields:
        - label: "Training times"
          name: "timetable"
          widget: "object"
          fields:
            - {label: "Harjoitusaika", name: "timetable_item", widget: "list", fields: 
              [
                {label: "Harjoituksen nimi", name: "name", widget: "string", hint: "For examle:. **Karate coloured belts** tai **Karaten basic course**"},
                {label: "1. harjoitusaika", name: "time1", widget: "string", hint: "Write in the form: **Monday 17:00-18:00**"},
                {label: "1. harjoituspaikka", name: "time1location", widget: "select", options: 
                [
                  "(Martial Arts Center, smaller side)",
                  "(Martial Arts Center, bigger side)"
                ]},
                {label: "2. harjoitusaika", name: "time2", widget: "string", required: false, hint: "Write in the form: **Monday 17:00-18:00**"},
                {label: "2. harjoituspaikka", name: "time2location", widget: "select", required: false, options: 
                [
                  "(Martial Arts Center, smaller side)",
                  "(Martial Arts Center, bigger side)"
                ]}
              ]}
        - label: "Coaches"
          name: "coaches"
          widget: "object"
          fields: 
            - {label: "Valmentaja", name: "coach_item", widget: "list", fields: [
                {label: "Valmentajan nimi", name: "name", widget: "string"},
                {label: "Vyön nimi", name: "belt", widget: "string", hint: "For example: **1. dan black belt**"},
                {label: "Vyön väri", name: "beltcolor", widget: "select", options: [
                      { label: "Musta", value: "#222" },
                      { label: "Purppura", value: "#5E3E8D" },
                      { label: "Ruskea", value: "#3f2a14" },
                      { label: "Sininen", value: "#355cb0" },
                      { label: "Ei tiedossa", value: "#DEDED9" }
                ]},
                {label: "Valmentajan kuva", name: "image", widget: "image", hint: "Ohje: 1. **Rajaa kuva neliön muotoiseksi**, niin että kasvot ja vyö näkyy. 2. **Poista kuvasta tausta** esim. tällä työkalulla: https://www.remove.bg/ 3. Muuta kuva tiedostomuotoon **.webp** esim. sivulla: https://webpconverter.org/ 4. Lopuksi nimeä tiedosto selkeästi valmentajan nimellä: **Roope Korpela.webp**"},
                {label: "Valmentajan rooli", name: "description", widget: "string", hint: "For example: **Basic course coach** or **Colored belts coach**"},
                {label: "Valmentajan ohjaajakoulutus", name: "description2", widget: "string", required: false, hint: "For example: **(1-tason junioriohjaaja)**"}
              ]}
        - {label: "Information for practitioners", name: "moreinfo", widget: "object", fields: [
              {label: "Sisältö", name: "content", widget: "markdown"}
            ]}  

